name: Build CI container

on:
  push:
    branches: [master]
    paths:
      - ".github/ci-containers/**"
      - "poetry.lock"
      - ".github/ci-container-build.yml"
  pull_request:
    branches: [master]
    paths:
      - ".github/ci-containers/**"
      - "poetry.lock"
      - ".github/ci-container-build.yml"

jobs:
  build-x86_64-ci-containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build images
        run: make x86_64
        working-directory: .github/ci-containers
      - name: Push images
        run: |
          echo ${GITHUB_TOKEN} | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin docker.pkg.github.com
          make push-x86_64
          docker logout docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: .github/ci-containers

  build-aarch64-ci-containers:
    runs-on: [self-hosted, linux, ARM64]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build images
        run: make aarch64
        working-directory: .github/ci-containers
      - name: Push images
        run: |
          echo ${GITHUB_TOKEN} | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin docker.pkg.github.com
          make push-aarch64
          docker logout docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: .github/ci-containers
