name: Build/publish documentation

on:
  push:
    branches: [master]
    tags: ["*"]

concurrency: doc_build

jobs:
  build:
    defaults: {run: {working-directory: deqr-docbuild}}
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/torque/deqr/linux-build:2_28_x86_64"
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          path: deqr-docbuild
      - name: Build
        run: |
          . "${DOCENV}"/bin/activate && "${POETRY}" install && sphinx-build -M html docs docs/_build
      - name: Environment variable fiddling (branch)
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        run: |
          printf "%s=%s\n" BRANCH_NAME "${GITHUB_REF#refs/heads/}" >> ${GITHUB_ENV}
          printf "%s=%s\n" COMMIT_REF ${{ github.sha }} >> ${GITHUB_ENV}
          printf "%s=%s\n" LINK_NAME latest-dev >> ${GITHUB_ENV}
      - name: Environment variable fiddling (tag)
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          printf "%s=%s\n" BRANCH_NAME "${GITHUB_REF#refs/tags/}" >> ${GITHUB_ENV}
          printf "%s=%s\n" COMMIT_REF "${GITHUB_REF#refs/tags/}" >> ${GITHUB_ENV}
          printf "%s=%s\n" LINK_NAME latest >> ${GITHUB_ENV}
      - name: Publish documentation
        run: |
          git clone https://${{ secrets.DOC_PUBLISH_USER }}:${{ secrets.DOC_PUBLISH_TOKEN }}@github.com/torque/deqr-docs.git
          rm -rf deqr-docs/${BRANCH_NAME}
          cp -a docs/_build/html/ deqr-docs/${BRANCH_NAME}
          rm -f deqr-docs/${LINK_NAME}
          cd deqr-docs
          git config user.name ${{ secrets.DOC_PUBLISH_USER }}
          git config user.email ${{ secrets.DOC_PUBLISH_USER }}@users.noreply.github.com
          ln -s ${BRANCH_NAME} ${LINK_NAME}
          git add ${LINK_NAME} ${BRANCH_NAME}
          if git commit -m "Commit ${{ github.repository }}@${COMMIT_REF}"; then
            git push origin
          fi
      - name: Cleanup
        if: ${{ always() }}
        run: |
          rm -rf deqr-docs
          git clean -fdx
