name: Publish with Poetry

on:
  push:
    tags: [ "*" ]

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry config virtualenvs.create false
        poetry install --no-root
    - name: Build
      run: |
        poetry build -f wheel
    - name: Publish
      run: |
        poetry publish --username="${{ secrets.PYPI_USERNAME}}" --password="${{ secrets.PYPI_PASSWORD }}"

  build-sdist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry config virtualenvs.create false
        poetry install --no-root
    - name: Build
      run: |
        poetry build -f sdist
    - name: Publish
      run: |
        poetry publish --username="${{ secrets.PYPI_USERNAME}}" --password="${{ secrets.PYPI_PASSWORD }}"
