name: Publish tagged builds

on:
  push:
    tags: [ "*" ]

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build poetry
      - name: Check version is coherent
        run: |
          python .github/workflows/version_check.py "deqr/__init__.py" "$(poetry version -s)"
      - name: Build
        run: |
          python -Im build -w
      - name: Publish
        run: |
          poetry publish --username="${{ secrets.PYPI_USERNAME}}" --password="${{ secrets.PYPI_PASSWORD }}"

  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build poetry
      - name: Check version is coherent
        run: |
          python .github/workflows/version_check.py "deqr/__init__.py" "$(poetry version -s)"
      - name: Build
        run: |
          python -Im build -s
      - name: Publish
        run: |
          poetry publish --username="${{ secrets.PYPI_USERNAME}}" --password="${{ secrets.PYPI_PASSWORD }}"

  build-wheels-linux:
    defaults: {run: {working-directory: deqr-publish}}
    runs-on: ${{ matrix.platform }}
    container:
      image: ghcr.io/torque/deqr/linux-build:${{ matrix.arch }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - [self-hosted, linux, ARM64]
          - ubuntu-latest
        include:
          - platform: [self-hosted, linux, ARM64]
            arch: 2_28_aarch64
          - platform: ubuntu-latest
            arch: 2_28_x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          path: deqr-publish
      - name: Check version is coherent
        run: |
          "${PY311}" .github/workflows/version_check.py "deqr/__init__.py" "$("${POETRY}" version -s)"
      - name: Build
        run: |
          echo "::group::Build for Python 3.8"
          "${PY38}" -Im build -w
          echo "::endgroup::"

          echo "::group::Clean Python 3.8 artifacts"
          git clean -fdxe dist
          echo "::endgroup::"

          echo "::group::Build for Python 3.9"
          "${PY39}" -Im build -w
          echo "::endgroup::"

          echo "::group::Clean Python 3.9 artifacts"
          git clean -fdxe dist
          echo "::endgroup::"

          echo "::group::Build for Python 3.10"
          "${PY310}" -Im build -w
          echo "::endgroup::"

          echo "::group::Clean Python 3.10 artifacts"
          git clean -fdxe dist
          echo "::endgroup::"

          echo "::group::Build for Python 3.11"
          "${PY311}" -Im build -w
          echo "::endgroup::"

          echo "::group::Clean Python 3.11 artifacts"
          git clean -fdxe dist
          echo "::endgroup::"
      - name: Publish
        run: |
          "${POETRY}" publish --username="${{ secrets.PYPI_USERNAME }}" --password="${{ secrets.PYPI_PASSWORD }}"
      - name: Cleanup
        if: ${{ always() }}
        run: git clean -fdx
